<a href="https://colab.research.google.com/github/Khang-lee/Gradutation-Project/blob/master/NUMPY_PYTHON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import pandas as pd
# --- 3.1. Array 1-chiều ---
#cách 1
# tạo list
my_list = [1, 9, 15, 39]
print('Python list:', my_list)
#chuyển list --> Numpy array
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

#cách 2
a = np.array([1, 9, 15, 39])
print(a)


# --- 3.2. Array 2-chiều ---
c = np.array([(1, 2, 3),
              (4, 5, 6)
             ])
print("--- 3.2 Array 2-chieu ---")
print(c)
print(c.shape)
print(c.dtype)
print("-" * 30)

# --- 3.3. Array 3-chiều ---
d = np.array([
              [[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])
print("--- 3.3 Array 3-chieu ---")
print(d)
print(d.shape)
print("-" * 30)

# --- 3.4. Tạo Array với giá trị ban đầu là 0 hoặc 1 ---
e_zeros = np.zeros((2, 2))
f_ones = np.ones((3, 3))
print("--- 3.4 Array 0 va 1 ---")
print('Zero matrix:\n', e_zeros)
print('One matrix:\n', f_ones)
print("-" * 30)

# 3.5.1. Reshape thay đổi kích thước ma trận
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print("--- 3.5.1 Reshape ---")
print(e)
print(e.shape)

f = e.reshape(3, 2)
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])
print(g)
print(g.shape)

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)
print("-" * 30)

# 3.5.2. Flatten là chuyển array nhiều chiều về 1 chiều
print("--- 3.5.2 Flatten ---")
e_flat = np.array([[1., 2., 3.], [4., 5., 6.]])
f_flat = e_flat.flatten()
print(f_flat)

g_flat = np.array([[[1., 2., 3.], [4., 5., 6.]],
                   [[7., 8., 9.], [10., 11., 12.]]
                  ])
j_flat = g_flat.flatten()
print(j_flat)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]
--- 3.2 Array 2-chieu ---
[[1 2 3]
 [4 5 6]]
(2, 3)
int64
------------------------------
--- 3.3 Array 3-chieu ---
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
------------------------------
--- 3.4 Array 0 va 1 ---
Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
------------------------------
--- 3.5.1 Reshape ---
[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]
------------------------------
--- 3.5.2 Flatten ---
[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
